package com.w3schools.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-05-18T11:57:16.351+05:30
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://www.w3schools.com/webservices/", name = "TempConvertHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TempConvertHttpPost {

    @WebResult(name = "string", targetNamespace = "http://www.w3schools.com/webservices/", partName = "Body")
    @WebMethod(operationName = "FahrenheitToCelsius")
    public java.lang.String fahrenheitToCelsius(
        @WebParam(partName = "Fahrenheit", name = "Fahrenheit", targetNamespace = "http://www.w3schools.com/webservices/")
        java.lang.String fahrenheit
    );

    @WebResult(name = "string", targetNamespace = "http://www.w3schools.com/webservices/", partName = "Body")
    @WebMethod(operationName = "CelsiusToFahrenheit")
    public java.lang.String celsiusToFahrenheit(
        @WebParam(partName = "Celsius", name = "Celsius", targetNamespace = "http://www.w3schools.com/webservices/")
        java.lang.String celsius
    );
}
